branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
      - "irc.mozilla.org#fireplace"
    on_success: change
    on_failure: change
  email: false
language: node_js
node_js:
  - "0.10"
before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
# Create an installation.
  - "npm install"
  - "make install"
  - "mv tests/settings_travis.js src/media/js/settings_local.js"
script:
# Lint the installation.
# - "commonplace lint"
# Generate langpacks, catches PO file errors.
  - "commonplace langpacks"
# Start the webserver.
  - "make serve &"
  - "sleep 5"
# Run UI tests.
  - "make test"
# Test package.
  - "make package"
  - "test -f package/builds/_prod/media/js/include.js"
